"use client";

import { useEffect, useState, type FormEvent } from "react";

import { useUiLanguage } from "../../../../components/ui/i18n";

type Block = { type: "heading" | "paragraph"; text: string } | { type: "list"; items: string[] };
type Citation = { chunkId: string; generationId: string; kind: "block"; fieldPath: null; blockOrder: number; quote: string; quoteSpanStart: number; quoteSpanEnd: number; page?: number | null; section?: string | null };
type Revision = { id: string; number: number; title: string; summary: string | null; body: string; blocks: Block[]; projection: Record<string, unknown>; citations: Citation[]; basedOnRevisionId: string | null; actor: string | null; reason: string | null; createdAt: string; lifecycle: string };
type Summary = { versionId: string; canonicalKey: string; entryType: EntryType; edition: string; language: string; versionLifecycle: string; publicationStatus: string; publicationAction: string | null };
type Detail = Summary & { sourceId: string; fileId: string; slug: string; aliases: string[]; activeRevisionId: string; canonicalRevisionId: string | null; revisions: Revision[]; publications: Array<{ id: string; action: string; status: string; actor: string; reason: string; lastError: string | null; createdAt: string }>; audit: Array<{ id: string; eventType: string; actor: string; reason: string; createdAt: string }> };
type Boundary = { sourceId: string; sourceTitle: string; edition: string; language: string; fileId: string; fileName: string };
type Chunk = { id: string; generationId: string; quote: string; page: number | null; section: string | null };
type EntryType = keyof typeof FIELDS;
type Field = { key: string; label: string; kind?: "number" | "boolean"; options?: readonly string[]; required?: boolean };

const SIZES = ["tiny","small","medium","large","huge","gargantuan"];
const FIELDS: Record<string, readonly Field[]> = {
  spell: [{key:"level",label:"Level",kind:"number",required:true},{key:"school",label:"School",options:["abjuration","conjuration","divination","enchantment","evocation","illusion","necromancy","transmutation"],required:true},{key:"castingTime",label:"Casting time",required:true},{key:"range",label:"Range",required:true},{key:"duration",label:"Duration",required:true},{key:"components",label:"Components",required:true},{key:"concentration",label:"Concentration",kind:"boolean"},{key:"ritual",label:"Ritual",kind:"boolean"}],
  creature: [{key:"size",label:"Size",options:SIZES,required:true},{key:"creatureType",label:"Creature type",required:true},{key:"alignment",label:"Alignment"},{key:"armorClass",label:"Armor class",kind:"number",required:true},{key:"hitPoints",label:"Hit points",kind:"number",required:true},{key:"challengeRating",label:"Challenge rating",kind:"number",required:true},{key:"speed",label:"Speed",required:true}],
  item: [{key:"category",label:"Category",options:["armor","potion","ring","rod","scroll","staff","wand","weapon","wondrous","other"],required:true},{key:"rarity",label:"Rarity",options:["common","uncommon","rare","very_rare","legendary","artifact","varies"],required:true},{key:"requiresAttunement",label:"Requires attunement",kind:"boolean"}],
  class: [{key:"hitDie",label:"Hit die",kind:"number",required:true},{key:"primaryAbility",label:"Primary ability",required:true},{key:"spellcastingAbility",label:"Spellcasting ability"}],
  feature: [{key:"level",label:"Level",kind:"number",required:true},{key:"featureKind",label:"Feature kind",required:true}],
  species: [{key:"size",label:"Size",options:SIZES,required:true},{key:"speed",label:"Speed",kind:"number",required:true}],
  background: [{key:"abilityScores",label:"Ability scores",required:true},{key:"skillProficiencies",label:"Skill proficiencies",required:true}],
  feat: [{key:"category",label:"Category",options:["origin","general","fighting_style","epic_boon"],required:true},{key:"prerequisiteLevel",label:"Prerequisite level",kind:"number"},{key:"prerequisiteText",label:"Prerequisite"},{key:"repeatable",label:"Repeatable",kind:"boolean"}],
  equipment: [{key:"category",label:"Category",options:["adventuring_gear","ammunition","armor","focus","mount","tool","vehicle","weapon","other"],required:true},{key:"costCp",label:"Cost (cp)",kind:"number"},{key:"weightLb",label:"Weight (lb)",kind:"number"}],
};
const TYPES = Object.keys(FIELDS) as EntryType[];
const INITIAL = { canonicalKey:"",entryType:"spell" as EntryType,edition:"5e",language:"en",sourceId:"",fileId:"",slug:"",aliases:"",title:"",summary:"",blocks:[{type:"paragraph",text:""}] as Block[],projection:{} as Record<string,unknown>,citations:[] as Citation[],reason:"" };

const COPY = {
  ru: { heading:"Структурный редактор",lede:"Безопасные типизированные блоки, доказательства и неизменяемые ревизии.",newEntry:"Новая запись",entries:"Записи",loading:"Загрузка…",empty:"Записей пока нет.",identity:"Идентичность",content:"Содержимое",evidence:"Источник и цитаты",history:"История ревизий",audit:"Журнал",title:"Название",summary:"Краткое описание",reason:"Причина изменения",save:"Сохранить новую ревизию",create:"Создать исходную запись",cancel:"Отмена",addParagraph:"Добавить абзац",addHeading:"Добавить заголовок",addList:"Добавить список",remove:"Удалить",moveUp:"Выше",moveDown:"Ниже",source:"Источник / файл",search:"Поиск по чанкам",selectCitation:"Добавить цитату",citations:"Выбранные цитаты",preview:"Превью",diff:"Сравнение",original:"Исходная ревизия",draft:"Текущая форма",publish:"Опубликовать через worker",unpublish:"Снять через worker",conflict:"Запись изменилась. Ваши данные и обе ревизии сохранены; обновите и согласуйте изменения.",cancelled:"Изменения формы отменены; сервер не изменялся.",aliases:"Псевдонимы через запятую",canonical:"Канонический ключ",slug:"Slug",type:"Тип",noChunks:"Подходящих чанков нет.",publication:"Публикация",unsafe:"HTML не принимается: блоки отображаются только как текст.",selectEntry:"Выберите запись или создайте новую.",retry:"Обновить",page:"стр." },
  en: { heading:"Structured entry editor",lede:"Safe typed blocks, source evidence, and immutable revisions.",newEntry:"New entry",entries:"Entries",loading:"Loading…",empty:"No entries yet.",identity:"Identity",content:"Content",evidence:"Source and citations",history:"Revision history",audit:"Audit trail",title:"Title",summary:"Summary",reason:"Change reason",save:"Save new revision",create:"Create original entry",cancel:"Cancel",addParagraph:"Add paragraph",addHeading:"Add heading",addList:"Add list",remove:"Remove",moveUp:"Move up",moveDown:"Move down",source:"Source / file",search:"Search chunks",selectCitation:"Add citation",citations:"Selected citations",preview:"Preview",diff:"Diff",original:"Original revision",draft:"Current form",publish:"Publish through worker",unpublish:"Unpublish through worker",conflict:"The entry changed. Your form and both revisions were preserved; reload and reconcile.",cancelled:"Form changes cancelled; no server mutation occurred.",aliases:"Comma-separated aliases",canonical:"Canonical key",slug:"Slug",type:"Type",noChunks:"No matching chunks.",publication:"Publication",unsafe:"HTML is never accepted; blocks render as text only.",selectEntry:"Select an entry or create a new one.",retry:"Reload",page:"p." },
} as const;

export function EntryEditor() {
  const { language } = useUiLanguage(); const c = COPY[language];
  const [entries,setEntries]=useState<Summary[]>([]); const [selected,setSelected]=useState<string|null>(null); const [detail,setDetail]=useState<Detail|null>(null);
  const [form,setForm]=useState(INITIAL); const [boundaries,setBoundaries]=useState<Boundary[]>([]); const [chunks,setChunks]=useState<Chunk[]>([]); const [search,setSearch]=useState("");
  const [error,setError]=useState<string|null>(null); const [notice,setNotice]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [previewId,setPreviewId]=useState<string|null>(null);

  async function json(url:string, options?:RequestInit) { const response=await fetch(url,options); const body=await response.json(); if(!response.ok) throw Object.assign(new Error(body.error??"Request failed"),{status:response.status}); return body; }
  async function loadEntries(){ const body=await json("/api/admin/compendium/entries"); setEntries(body.entries); }
  async function loadDetail(id:string, preferredRevisionId?:string){ const body=await json(`/api/admin/compendium/entries/${id}`); const next=body.entry as Detail; setDetail(next); const base=next.revisions.find((r)=>r.id===(preferredRevisionId??next.activeRevisionId))??next.revisions[0]; setForm({canonicalKey:next.canonicalKey,entryType:next.entryType,edition:next.edition,language:next.language,sourceId:next.sourceId,fileId:next.fileId,slug:next.slug,aliases:next.aliases.join(", "),title:base.title,summary:base.summary??"",blocks:base.blocks,projection:base.projection,citations:base.citations,reason:""}); setPreviewId(base.id); setError(null); }
  async function loadEvidence(sourceId?:string,fileId?:string,q=""){ const params=new URLSearchParams(); if(sourceId&&fileId){params.set("sourceId",sourceId);params.set("fileId",fileId);if(q)params.set("q",q);} const body=await json(`/api/admin/compendium/entries/evidence?${params}`); setBoundaries(body.boundaries); setChunks(body.chunks); }
  useEffect(()=>{ const timer=setTimeout(()=>void Promise.all([loadEntries(),loadEvidence()]).catch((reason)=>setError(reason.message)),0); return()=>clearTimeout(timer); },[]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{ if(!form.sourceId||!form.fileId)return; const timer=setTimeout(()=>void loadEvidence(form.sourceId,form.fileId,search).catch((reason)=>setError(reason.message)),250); return()=>clearTimeout(timer); },[form.sourceId,form.fileId,search]); // eslint-disable-line react-hooks/exhaustive-deps

  function startNew(){ setSelected(null);setDetail(null);setPreviewId(null);setChunks([]);setSearch("");setForm({...INITIAL,blocks:[{type:"paragraph",text:""}],projection:{}});setNotice(null);setError(null); }
  function selectBoundary(value:string){ const boundary=boundaries.find((item)=>`${item.sourceId}:${item.fileId}`===value); if(!boundary)return; setForm((current)=>({...current,sourceId:boundary.sourceId,fileId:boundary.fileId,edition:boundary.edition,language:boundary.language,citations:[]})); }
  function projection(){ const value:Record<string,unknown>={type:form.entryType}; for(const field of FIELDS[form.entryType]){ const raw=form.projection[field.key]; if(field.kind==="boolean") value[field.key]=Boolean(raw); else if(field.kind==="number") { if(raw!==""&&raw!=null)value[field.key]=Number(raw); } else if(raw!==""&&raw!=null)value[field.key]=raw; } return value; }
  async function save(event:FormEvent){ event.preventDefault();setBusy(true);setError(null);setNotice(null); try { const payload={title:form.title,summary:form.summary||null,blocks:form.blocks,projection:projection(),citations:form.citations.map(citationPayload),reason:form.reason}; if(selected&&detail){ const body=await json(`/api/admin/compendium/entries/${selected}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payload,basedOnRevisionId:detail.activeRevisionId})}); await loadDetail(selected,body.revisionId); } else { const body=await json("/api/admin/compendium/entries",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payload,canonicalKey:form.canonicalKey,entryType:form.entryType,edition:form.edition,language:form.language,sourceId:form.sourceId,fileId:form.fileId,slug:form.slug,aliases:form.aliases.split(",").map((x)=>x.trim()).filter(Boolean)})}); setSelected(body.versionId);await Promise.all([loadEntries(),loadDetail(body.versionId)]); } } catch(reason){ const e=reason as Error&{status?:number};setError(e.status===409?c.conflict:e.message); } finally{setBusy(false);} }
  async function publication(action:"publish"|"unpublish"){ if(!detail||!form.reason.trim())return setError(c.reason); if(action==="unpublish"&&!confirm(c.unpublish+"?"))return; setBusy(true);try{ const revision=detail.revisions[0];await json(`/api/admin/compendium/entries/${detail.versionId}/publication`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,revisionId:action==="publish"?revision.id:undefined,expectedActiveRevisionId:detail.canonicalRevisionId,reason:form.reason})});await loadDetail(detail.versionId); }catch(reason){const e=reason as Error&{status?:number};setError(e.status===409?c.conflict:e.message);}finally{setBusy(false);} }
  function cancel(){ if(detail)void loadDetail(detail.versionId);else startNew();setNotice(c.cancelled); }
  function updateBlock(index:number, block:Block){ setForm((current)=>({...current,blocks:current.blocks.map((item,i)=>i===index?block:item)})); }
  function moveBlock(index:number,delta:number){setForm((current)=>{const blocks=[...current.blocks];const target=index+delta;if(target<0||target>=blocks.length)return current;[blocks[index],blocks[target]]=[blocks[target],blocks[index]];return{...current,blocks};});}
  const shownRevision=detail?.revisions.find((revision)=>revision.id===previewId)??null;
  return <div className="space-y-6"><header className="border-b border-border pb-5"><h1 className="text-3xl">{c.heading}</h1><p className="mt-2 text-text-muted">{c.lede}</p></header>
    {error&&<p role="alert" className="rounded-lg border border-danger/30 bg-danger/10 p-3 text-danger">{error} <button className="ml-2 underline" onClick={()=>selected&&void loadDetail(selected)}>{c.retry}</button></p>}{notice&&<p role="status" className="rounded-lg bg-success/10 p-3 text-success">{notice}</p>}
    <div className="grid gap-6 xl:grid-cols-[17rem_minmax(0,1fr)]"><aside className="min-w-0 rounded-xl border border-border bg-surface p-4"><div className="flex items-center justify-between"><h2>{c.entries}</h2><button onClick={startNew} className="rounded-md bg-accent px-3 py-2 text-sm font-bold text-white">{c.newEntry}</button></div><div className="mt-4 max-h-[70vh] space-y-2 overflow-auto">{entries.length===0&&<p className="text-sm text-text-muted">{c.empty}</p>}{entries.map((entry)=><button key={entry.versionId} onClick={()=>{setSelected(entry.versionId);void loadDetail(entry.versionId).catch((reason)=>setError(reason.message));}} className={`w-full rounded-md border p-3 text-left ${selected===entry.versionId?"border-accent bg-accent/10":"border-border bg-surface-light"}`}><strong className="block break-words">{entry.canonicalKey}</strong><span className="text-xs text-text-muted">{entry.entryType} · {entry.edition} · {entry.language}</span><span className="mt-1 block text-xs">{entry.publicationAction??"draft"}: {entry.publicationStatus}</span></button>)}</div></aside>
      <main className="min-w-0">{!selected&&!detail&&form===INITIAL?<p>{c.selectEntry}</p>:<form onSubmit={save} className="space-y-5"><section className="rounded-xl border border-border bg-surface p-4 sm:p-5"><h2>{c.identity}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><FieldLabel label={c.canonical}><input disabled={Boolean(detail)} required value={form.canonicalKey} onChange={(e)=>setForm({...form,canonicalKey:e.target.value})}/></FieldLabel><FieldLabel label={c.slug}><input disabled={Boolean(detail)} required value={form.slug} onChange={(e)=>setForm({...form,slug:e.target.value})}/></FieldLabel><FieldLabel label={c.type}><select disabled={Boolean(detail)} value={form.entryType} onChange={(e)=>setForm({...form,entryType:e.target.value as EntryType,projection:{}})}>{TYPES.map((type)=><option key={type}>{type}</option>)}</select></FieldLabel><FieldLabel label={c.aliases}><input disabled={Boolean(detail)} value={form.aliases} onChange={(e)=>setForm({...form,aliases:e.target.value})}/></FieldLabel><FieldLabel label={c.source}><select disabled={Boolean(detail)} required value={form.sourceId&&form.fileId?`${form.sourceId}:${form.fileId}`:""} onChange={(e)=>selectBoundary(e.target.value)}><option value="">—</option>{boundaries.map((b)=><option key={`${b.sourceId}:${b.fileId}`} value={`${b.sourceId}:${b.fileId}`}>{b.sourceTitle} · {b.fileName} · {b.edition}/{b.language}</option>)}</select></FieldLabel></div></section>
        <section className="rounded-xl border border-border bg-surface p-4 sm:p-5"><h2>{c.content}</h2><p className="mt-1 text-xs text-text-muted">{c.unsafe}</p><div className="mt-4 grid gap-4 lg:grid-cols-2"><FieldLabel label={c.title}><input required value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/></FieldLabel><FieldLabel label={c.summary}><input value={form.summary} onChange={(e)=>setForm({...form,summary:e.target.value})}/></FieldLabel></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{FIELDS[form.entryType].map((field)=><ProjectionField key={field.key} field={field} value={form.projection[field.key]} onChange={(value)=>setForm({...form,projection:{...form.projection,[field.key]:value}})}/>)}</div><div className="mt-5 space-y-3">{form.blocks.map((block,index)=><div key={index} className="rounded-lg border border-border bg-surface-light p-3"><div className="mb-2 flex flex-wrap items-center justify-between gap-2"><strong className="text-xs uppercase">{block.type} {index+1}</strong><span className="flex gap-1"><SmallButton label={c.moveUp} disabled={index===0} onClick={()=>moveBlock(index,-1)}/><SmallButton label={c.moveDown} disabled={index===form.blocks.length-1} onClick={()=>moveBlock(index,1)}/><SmallButton label={c.remove} disabled={form.blocks.length===1} onClick={()=>setForm({...form,blocks:form.blocks.filter((_,i)=>i!==index)})}/></span></div>{block.type==="list"?<textarea aria-label={`list ${index+1}`} required value={block.items.join("\n")} onChange={(e)=>updateBlock(index,{type:"list",items:e.target.value.split("\n")})}/>:<textarea aria-label={`${block.type} ${index+1}`} required value={block.text} onChange={(e)=>updateBlock(index,{...block,text:e.target.value})}/>}</div>)}</div><div className="mt-3 flex flex-wrap gap-2"><SmallButton label={c.addParagraph} onClick={()=>setForm({...form,blocks:[...form.blocks,{type:"paragraph",text:""}]})}/><SmallButton label={c.addHeading} onClick={()=>setForm({...form,blocks:[...form.blocks,{type:"heading",text:""}]})}/><SmallButton label={c.addList} onClick={()=>setForm({...form,blocks:[...form.blocks,{type:"list",items:[""]}]})}/></div></section>
        <section className="rounded-xl border border-border bg-surface p-4 sm:p-5"><h2>{c.evidence}</h2><FieldLabel label={c.search}><input value={search} onChange={(e)=>setSearch(e.target.value)}/></FieldLabel><div className="mt-4 grid max-h-96 gap-3 overflow-auto md:grid-cols-2">{chunks.length===0&&<p className="text-sm text-text-muted">{c.noChunks}</p>}{chunks.map((chunk)=><article key={chunk.id} className="rounded-lg border border-border bg-surface-light p-3"><p className="line-clamp-4 text-sm whitespace-pre-wrap">{chunk.quote}</p><p className="mt-2 text-xs text-text-muted">{chunk.section??"—"} · {c.page} {chunk.page??"—"}</p><div className="mt-2 flex gap-2"><button type="button" disabled={form.citations.some((x)=>x.chunkId===chunk.id)} onClick={()=>setForm({...form,citations:[...form.citations,{chunkId:chunk.id,generationId:chunk.generationId,kind:"block",fieldPath:null,blockOrder:form.citations.length,quote:chunk.quote,quoteSpanStart:0,quoteSpanEnd:Array.from(chunk.quote).length,page:chunk.page,section:chunk.section}]})} className="rounded bg-accent px-2 py-1 text-xs font-bold text-white disabled:opacity-40">{c.selectCitation}</button>{chunk.page&&<a target="_blank" rel="noreferrer" className="rounded border border-accent px-2 py-1 text-xs text-accent" href={`/api/citations/preview?sourceId=${form.sourceId}&fileId=${form.fileId}&page=${chunk.page}`}>{c.preview}</a>}</div></article>)}</div><h3 className="mt-4 text-sm font-bold">{c.citations} ({form.citations.length})</h3>{form.citations.map((citation,index)=><div key={citation.chunkId} className="mt-2 flex items-start justify-between gap-3 rounded bg-primary/10 p-2 text-xs"><span>{citation.quote.slice(0,180)} · {c.page} {citation.page??"—"}</span><button type="button" aria-label={`${c.remove} ${index+1}`} onClick={()=>setForm({...form,citations:form.citations.filter((_,i)=>i!==index).map((item,i)=>({...item,blockOrder:i}))})} className="text-danger underline">{c.remove}</button></div>)}</section>
        <section className="rounded-xl border border-border bg-surface p-4 sm:p-5"><h2>{c.diff} / {c.preview}</h2><div className="mt-4 grid gap-4 lg:grid-cols-2"><TextPreview title={c.original} revision={shownRevision}/><TextPreview title={c.draft} revision={{title:form.title,summary:form.summary,blocks:form.blocks} as Revision}/></div></section>
        <FieldLabel label={c.reason}><textarea required maxLength={1000} value={form.reason} onChange={(e)=>setForm({...form,reason:e.target.value})}/></FieldLabel><div className="flex flex-wrap gap-2"><button disabled={busy} className="rounded-md bg-accent px-4 py-2 font-bold text-white disabled:opacity-40">{detail?c.save:c.create}</button><button type="button" onClick={cancel} className="rounded-md border border-border px-4 py-2">{c.cancel}</button>{detail&&<><button type="button" disabled={busy} onClick={()=>void publication("publish")} className="rounded-md bg-success px-4 py-2 font-bold text-white">{c.publish}</button><button type="button" disabled={busy||detail.canonicalRevisionId===null} onClick={()=>void publication("unpublish")} className="rounded-md bg-danger px-4 py-2 font-bold text-white disabled:opacity-40">{c.unpublish}</button></>}</div></form>}
        {detail&&<div className="mt-6 grid gap-5 lg:grid-cols-2"><section className="rounded-xl border border-border bg-surface p-4"><h2>{c.history}</h2>{detail.revisions.map((revision)=><button key={revision.id} onClick={()=>setPreviewId(revision.id)} className="mt-2 block w-full rounded border border-border p-3 text-left"><strong>#{revision.number} {revision.title}</strong><span className="block text-xs text-text-muted">{revision.actor??"system"} · {new Date(revision.createdAt).toLocaleString(language)} · {revision.reason??"—"}</span></button>)}</section><section className="rounded-xl border border-border bg-surface p-4"><h2>{c.audit}</h2>{detail.audit.map((event)=><p key={event.id} className="mt-2 border-t border-border-light pt-2 text-xs"><strong>{event.eventType}</strong> · {event.actor} · {new Date(event.createdAt).toLocaleString(language)}<span className="block">{event.reason}</span></p>)}</section></div>}</main></div></div>;
}

function FieldLabel({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-bold [&_input]:mt-1 [&_input]:w-full [&_input]:rounded-md [&_input]:border [&_input]:border-border [&_input]:bg-surface-light [&_input]:p-2 [&_select]:mt-1 [&_select]:w-full [&_select]:rounded-md [&_select]:border [&_select]:border-border [&_select]:bg-surface-light [&_select]:p-2 [&_textarea]:mt-1 [&_textarea]:min-h-24 [&_textarea]:w-full [&_textarea]:rounded-md [&_textarea]:border [&_textarea]:border-border [&_textarea]:bg-surface-light [&_textarea]:p-2">{label}{children}</label>}
function ProjectionField({field,value,onChange}:{field:Field;value:unknown;onChange:(value:unknown)=>void}){if(field.kind==="boolean")return <label className="flex items-center gap-2 self-end rounded-md border border-border p-2 text-sm font-bold"><input type="checkbox" checked={Boolean(value)} onChange={(e)=>onChange(e.target.checked)}/>{field.label}</label>;return <FieldLabel label={field.label}>{field.options?<select required={field.required} value={String(value??"")} onChange={(e)=>onChange(e.target.value)}><option value="">—</option>{field.options.map((option)=><option key={option}>{option}</option>)}</select>:<input required={field.required} type={field.kind==="number"?"number":"text"} step="any" value={String(value??"")} onChange={(e)=>onChange(e.target.value)}/>}</FieldLabel>}
function SmallButton({label,onClick,disabled=false}:{label:string;onClick:()=>void;disabled?:boolean}){return <button type="button" disabled={disabled} onClick={onClick} className="rounded border border-border px-2 py-1 text-xs disabled:opacity-30">{label}</button>}
function TextPreview({title,revision}:{title:string;revision:Revision|null}){return <article><h3 className="text-sm font-bold">{title}</h3><div className="mt-2 min-h-40 rounded-lg bg-primary/10 p-4"><strong>{revision?.title||"—"}</strong>{revision?.summary&&<p className="mt-1 text-sm text-text-muted">{revision.summary}</p>}<div className="mt-3 space-y-2">{revision?.blocks?.map((block,index)=>block.type==="heading"?<h4 key={index} className="font-bold">{block.text}</h4>:block.type==="list"?<ul key={index} className="list-disc pl-5">{block.items.map((item,i)=><li key={i}>{item}</li>)}</ul>:<p key={index} className="whitespace-pre-wrap">{block.text}</p>)}</div></div></article>}
function citationPayload(citation:Citation){return {chunkId:citation.chunkId,generationId:citation.generationId,kind:citation.kind,fieldPath:citation.fieldPath,blockOrder:citation.blockOrder,quote:citation.quote,quoteSpanStart:citation.quoteSpanStart,quoteSpanEnd:citation.quoteSpanEnd};}
