import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { classifyCandidatePublication, projectSnapshotCreatureCandidate } from "../../src/server/compendium/candidate-publication.ts";
import { parseCreatureListOptions } from "../../src/server/compendium/creature-http.ts";
import { CreatureReadService } from "../../src/server/compendium/creature-read-service.ts";
import { challengeRatingNumber, formatChallengeRating, validateCreatureProjection } from "../../src/server/compendium/creature-schema.ts";
import { creatureCandidate, creatureMetadataEvidence } from "../../src/server/compendium/next-dnd/import-adapter.ts";
import { projectCanonicalRevisions } from "../../src/server/content-index/projection.ts";
import { nfsIndexEntryRow } from "../../src/server/content-index/sync.ts";
import { ancientDragonDetail } from "../fixtures/next-dnd/bestiary.mts";

const detail = ancientDragonDetail();
const source = { schemaVersion:1,kind:"source",sourceId:"next-dnd-bestiary",title:"Next D&D Bestiary",category:"official_supplement",edition:"5.5e",language:"ru",accessTier:"open",shared:false,ownerUserId:null,publication:{code:"NEXT",title:"Next D&D",publisher:"next.dnd.su",releaseYear:2026,revision:"2026-08-07",sourcePriority:10,canonicalBookId:"next-dnd"},files:[{fileId:"22222222-2222-4222-8222-222222222222",path:"sources/next-dnd-bestiary/files/22222222-2222-4222-8222-222222222222.snapshot",mediaType:"application/x-next-dnd-snapshot",contentHash:`sha256:${"d".repeat(64)}`}]} as const;
const evidence = { sourceUrl:detail.sourceUrl,fingerprintSha256:detail.sha256,rawBlobPath:detail.blobPath,fetchedAt:detail.fetchedAt,fileChecksumSha256:"d".repeat(64),indexUrl:detail.indexSource.url,indexFingerprintSha256:detail.indexSource.fingerprintSha256,rawIndexBlobPath:detail.indexSource.rawBlobPath,indexFetchedAt:detail.indexSource.fetchedAt,indexCardFingerprintSha256:detail.indexSource.cardFingerprintSha256,metadataEvidenceText:creatureMetadataEvidence(detail.indexMetadata) };

test("complex collector creature round-trips every controlled stat-block section with immutable citations", () => { const candidate=creatureCandidate(detail as never); assert.equal(candidate.extraction.status,"ready"); const creature=validateCreatureProjection(candidate.attributes); assert.deepEqual(creature.challengeRating,{numerator:24,denominator:1}); assert.equal(creature.speeds.length,3); assert.equal(creature.abilities.str,30); assert.equal(creature.traits.length,2); assert.equal(creature.actions.length,2); assert.equal(creature.bonusActions.length,1); assert.equal(creature.reactions.length,1); assert.equal(creature.legendaryActions.length,2); assert.equal(candidate.citations.length,23); assert.equal(classifyCandidatePublication(candidate,{candidateKey:"bestiary-999",entryType:"creature",sourceId:"11111111-1111-4111-8111-111111111111",fileId:source.files[0].fileId,generationId:null,edition:"5.5e",language:"ru",accessTier:"open",shared:false,ownerUserId:null,chunk:null,snapshotEvidence:evidence}).publicationCapability,"publishable"); const revision=projectSnapshotCreatureCandidate(candidate,{candidateKey:"bestiary-999",createdAt:detail.fetchedAt,source,fileId:source.files[0].fileId,evidence}); assert.equal(revision.entry.entryType,"monster"); assert.equal(revision.citations.length,23); assert.equal(revision.citations.every((citation)=>citation.fieldPath&&citation.page===null),true); assert.equal(JSON.stringify(revision).includes("contentHtml"),false); });

test("exact rational CR parses, orders numerically, and restores filters", () => { const options=parseCreatureListOptions(new URL("https://example.test/bestiary?size=large&type=dragon&cr=1%2F8&cr=1%2F2&crMin=1%2F4&crMax=2&language=ru")); assert.deepEqual(options.challenges?.map(formatChallengeRating),["1/8","1/2"]); assert.deepEqual(options.sizes,["large"]); assert.equal(challengeRatingNumber(options.minChallenge!),.25); assert.equal(challengeRatingNumber(options.maxChallenge!),2); });

test("RBAC, counts, numeric CR keyset ordering, and NFS reads share one boundary", async () => { const candidate=creatureCandidate(detail as never); const revision=projectSnapshotCreatureCandidate(candidate,{candidateKey:"bestiary-999",createdAt:detail.fetchedAt,source,fileId:source.files[0].fileId,evidence}); const [projection]=projectCanonicalRevisions("fixture",[revision],[{sourceId:source.sourceId,fileId:source.files[0].fileId,path:source.files[0].path,mediaType:source.files[0].mediaType,contentHash:source.files[0].contentHash,byteSize:4096}]); const synced=nfsIndexEntryRow("fixture",projection); const row={...synced,mime_type:source.files[0].mediaType,source_title:source.title,edition:source.edition,language:source.language,publication_code:source.publication.code,publication_revision:source.publication.revision,source_priority:10,sort_title:synced.name.toLowerCase(),cr_value:"24",source_versions:[]}; const statements:string[]=[]; const service=new CreatureReadService({async query(sql:string){statements.push(sql);return sql.includes("count(*)")?{rows:[{count:"1"}]}:{rows:[row]};}}); const result=await service.list({role:"user"},{minChallenge:{numerator:1,denominator:8},limit:1}); assert.equal(result.count,1); assert.equal(result.creatures[0].legendaryActions.length,2); assert.match(statements[0],/s\.access_tier = 'open'/); assert.match(statements[0],/n\.entry_type='monster'/); assert.match(statements[0],/ORDER BY creature\.cr_value/); assert.doesNotMatch(statements[1],/creature\.cr_value,creature\.sort_title[\s\S]*>/); });

test("bestiary UI retains RU/EN, mobile, print, and controlled rendering contracts", async () => { const [i18n,css,list,view,migration]=await Promise.all([readFile("src/components/ui/i18n.tsx","utf8"),readFile("src/app/globals.css","utf8"),readFile("src/app/bestiary/bestiary-list.tsx","utf8"),readFile("src/app/bestiary/[identifier]/bestiary-detail.tsx","utf8"),readFile("migrations/0018_bestiary_stat_blocks.sql","utf8")]); assert.match(i18n,/bestiaryCatalog: "Бестиарий"/); assert.match(i18n,/bestiaryCatalog: "Bestiary"/); assert.match(css,/@media \(max-width: 39\.999rem\)[\s\S]*\.bestiary-filters/); assert.match(css,/@media print[\s\S]*\.bestiary-citations/); assert.match(list,/name="crMin"/); assert.match(view,/BlockSection/); assert.doesNotMatch(view,/dangerouslySetInnerHTML/); assert.match(migration,/challenge_rating_numerator/); assert.match(migration,/legendary_actions/); });
