"use client";
import Link from "next/link";
import { useUiLanguage } from "../../../components/ui/i18n";
import { ABILITY_KEYS, formatChallengeRating, type CreatureBlock } from "../../../server/compendium/creature-schema";
import type { CreatureDetail } from "../../../server/compendium/creature-read-service";
function BlockSection({ title, blocks }: Readonly<{ title: string; blocks: readonly CreatureBlock[] }>) { return blocks.length ? <section className="stat-block-section"><h2>{title}</h2>{blocks.map((block, index) => <div className="stat-block-feature" key={`${block.name}-${index}`}><h3>{block.name}</h3><p>{block.text}</p></div>)}</section> : null; }
export function BestiaryDetail({ creature, returnHref }: Readonly<{ creature: CreatureDetail; returnHref: string }>) { const { t } = useUiLanguage(); const modifier = (score: number) => `${Math.floor((score - 10) / 2) >= 0 ? "+" : ""}${Math.floor((score - 10) / 2)}`; const facts = [[t("armorClass"), creature.armorClass.map((item) => `${item.value}${item.note ? ` (${item.note})` : ""}`).join(", ")], [t("hitPoints"), `${creature.hitPoints.average}${creature.hitPoints.formula ? ` (${creature.hitPoints.formula})` : ""}`], [t("speed"), creature.speeds.map((item) => `${t(`speed${item.mode[0].toUpperCase()}${item.mode.slice(1)}` as never)} ${item.distance} ${item.unit}${item.note ? ` (${item.note})` : ""}`).join(", ")]]; return <article className="bestiary-detail stat-block">
  <Link className="bestiary-back print-action" href={returnHref}>← {t("backToBestiary")}</Link><header><div><p>D&D {creature.edition}</p><h1>{creature.title}</h1><p>{creature.size} {creature.creatureType}{creature.alignment ? `, ${creature.alignment}` : ""}</p></div><span className="cr-badge">CR {formatChallengeRating(creature.challengeRating)}</span></header>
  <dl className="stat-block-facts">{facts.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><dl className="ability-grid">{ABILITY_KEYS.map((key) => <div key={key}><dt>{key.toUpperCase()}</dt><dd>{creature.abilities[key]} ({modifier(creature.abilities[key])})</dd></div>)}</dl>
  <dl className="stat-block-lines"><div><dt>{t("savingThrows")}</dt><dd>{formatMap(creature.saves)}</dd></div><div><dt>{t("skills")}</dt><dd>{formatMap(creature.skills)}</dd></div><div><dt>{t("damageResistances")}</dt><dd>{formatList(creature.damageResistances)}</dd></div><div><dt>{t("damageImmunities")}</dt><dd>{formatList(creature.damageImmunities)}</dd></div><div><dt>{t("conditionImmunities")}</dt><dd>{formatList(creature.conditionImmunities)}</dd></div><div><dt>{t("senses")}</dt><dd>{formatList(creature.senses)}; {t("passivePerception")} {creature.passivePerception}</dd></div><div><dt>{t("languages")}</dt><dd>{formatList(creature.languages)}</dd></div></dl>
  <BlockSection title={t("traits")} blocks={creature.traits} /><BlockSection title={t("actions")} blocks={creature.actions} /><BlockSection title={t("bonusActions")} blocks={creature.bonusActions} /><BlockSection title={t("reactions")} blocks={creature.reactions} /><BlockSection title={t("legendaryActions")} blocks={creature.legendaryActions} />
  <section className="source-attribution"><h2>{t("sourceDetails")}</h2><p>{creature.source.code ?? creature.source.title}{creature.source.revision ? ` · ${creature.source.revision}` : ""} · <a className="print-action" href={`/api/sources/${encodeURIComponent(creature.source.id)}`}>{t("sourceDetails")}</a></p></section>
  <section className="source-versions"><h2>{t("sourceVersions")}</h2><ul>{creature.sourceVersions.map((source) => <li key={`${source.sourceId}-${source.revisionId}`}>{source.code ?? source.title}{source.revision ? ` · ${source.revision}` : ""} · <code>{source.revisionId}</code></li>)}</ul></section>
  {creature.sourceVersion ? <section className="collector-version"><h2>{t("collectorVersion")}</h2><p><a className="print-action" href={creature.sourceVersion.url}>{creature.sourceVersion.url}</a><span className="print-source-text">{creature.sourceVersion.url}</span></p><code>{creature.sourceVersion.fingerprintSha256}</code></section> : null}
  <section className="bestiary-citations"><h2>{t("citations")}</h2>{creature.citations.map((citation) => <blockquote key={citation.id}><p>“{citation.quote}”</p><footer>{citation.fieldPath ? <code>{citation.fieldPath}</code> : citation.section}{citation.page === null ? "" : ` · ${t("pageShort")} ${citation.page}`}{citation.previewUrl ? <> · <a className="print-action citation-action" href={citation.previewUrl}>{t("openPdfCitation")}</a></> : citation.sourceUrl ? <> · <a className="print-action citation-action" href={citation.sourceUrl}>{t("openExternalCitation")}</a><span className="print-source-text"> · {citation.sourceUrl}</span></> : null} · <a className="print-action citation-action" href={citation.sourceDetailUrl}>{t("sourceDetails")}</a></footer></blockquote>)}</section>
</article>; }
function formatMap(value: Readonly<Record<string, number>>): string { const result = Object.entries(value).map(([key, modifier]) => `${key} ${modifier >= 0 ? "+" : ""}${modifier}`).join(", "); return result || "—"; } function formatList(value: readonly string[]): string { return value.join(", ") || "—"; }
