import type { QueryResultRow } from "pg";
import { buildSourceAccessSql } from "../access/access-sql.ts";
import { buildRetrievalAuthorizationFilter, type RetrievalSelection, type RetrievalUser } from "../access/retrieval-filter.ts";
import { query } from "../db/client.ts";
import { challengeRatingNumber, creatureProjectionFromTypedFields, type ChallengeRating, type CreatureProjection, type CreatureSize } from "./creature-schema.ts";

type Queryable = Readonly<{ query<T extends QueryResultRow = QueryResultRow>(sql: string, values?: readonly unknown[]): Promise<{ rows: T[] }> }>;
export type CreatureListOptions = RetrievalSelection & Readonly<{ sizes?: readonly CreatureSize[]; types?: readonly string[]; alignment?: string; challenges?: readonly ChallengeRating[]; minChallenge?: ChallengeRating; maxChallenge?: ChallengeRating; query?: string; cursor?: string; limit?: number }>;
export type CreatureCitation = Readonly<{ id: string; quote: string; section: string; page: number | null; sourceId: string; fileId: string; previewUrl: string | null; sourceUrl: string | null; sourceDetailUrl: string; fieldPath: string | null }>;
export type CreatureListEntry = CreatureProjection & Readonly<{ id: string; revisionId: string; title: string; aliases: readonly string[]; summary: string; edition: string; language: string; source: Readonly<{ id: string; title: string; code: string | null; revision: string | null }> }>;
export type CreatureDetail = CreatureListEntry & Readonly<{ body: string; citations: readonly CreatureCitation[]; sourceVersions: readonly Readonly<{ sourceId: string; title: string; code: string | null; revision: string | null; revisionId: string }>[]; sourceVersion: Readonly<{ url: string; fingerprintSha256: string; rawBlobPath: string; fetchedAt: string; fileChecksumSha256: string; index: Readonly<{ url: string; fingerprintSha256: string; rawBlobPath: string; fetchedAt: string; cardFingerprintSha256: string }> }> | null }>;
export class CreatureReadInputError extends Error {}
export class CreatureNotFoundError extends Error {}
type CreatureRow = QueryResultRow & Readonly<{ entry_id: string; revision_id: string; name: string; aliases: unknown; typed_fields: unknown; plain_text: string; canonical_payload: Record<string, unknown>; source_id: string; file_id: string; mime_type: string; source_title: string; edition: string; language: string; publication_code: string | null; publication_revision: string | null; source_versions: unknown; sort_title: string; cr_value: string }>;
const database: Queryable = { query };

export class CreatureReadService {
  private readonly db: Queryable;
  constructor(db: Queryable = database) { this.db = db; }
  async list(user: RetrievalUser, options: CreatureListOptions = {}): Promise<Readonly<{ creatures: readonly CreatureListEntry[]; count: number; nextCursor: string | null }>> {
    validateOptions(options); const boundary = boundarySql(user, options); const filters = creatureFilters(boundary.params, options); const limit = options.limit ?? 24; boundary.params.push(limit + 1);
    const result = await this.db.query<CreatureRow>(`${boundary.sql} SELECT * FROM accessible_creatures creature WHERE ${filters} ORDER BY creature.cr_value, creature.sort_title COLLATE "C", creature.entry_id LIMIT $${boundary.params.length}`, boundary.params);
    const visible = result.rows.slice(0, limit); const countOptions = { ...options }; delete countOptions.cursor; delete countOptions.limit;
    const count = await this.count(user, countOptions); const last = visible.at(-1);
    return { creatures: visible.map(mapList), count, nextCursor: result.rows.length > limit && last ? encodeCursor(last) : null };
  }
  async count(user: RetrievalUser, options: Omit<CreatureListOptions, "limit" | "cursor"> = {}): Promise<number> { validateOptions(options); const boundary = boundarySql(user, options); const filters = creatureFilters(boundary.params, options); const result = await this.db.query<{ count: string } & QueryResultRow>(`${boundary.sql} SELECT count(*)::text AS count FROM accessible_creatures creature WHERE ${filters}`, boundary.params); return Number(result.rows[0]?.count ?? 0); }
  async get(user: RetrievalUser, identifier: string, selection: RetrievalSelection = {}): Promise<CreatureDetail> { const normalized = normalizeIdentifier(identifier); const boundary = boundarySql(user, selection); boundary.params.push(normalized); const result = await this.db.query<CreatureRow>(`${boundary.sql} SELECT * FROM accessible_creatures creature WHERE creature.entry_id = $${boundary.params.length} OR EXISTS (SELECT 1 FROM jsonb_array_elements_text(creature.aliases) alias WHERE compendium_normalize_name(alias) = compendium_normalize_name($${boundary.params.length})) ORDER BY creature.source_priority DESC, creature.revision_id LIMIT 1`, boundary.params); if (!result.rows[0]) throw new CreatureNotFoundError(); return mapDetail(result.rows[0]); }
}

function boundarySql(user: RetrievalUser, selection: RetrievalSelection): { sql: string; params: unknown[] } { const access = buildSourceAccessSql(buildRetrievalAuthorizationFilter(user, selection)); return { params: [...access.params], sql: `WITH accessible_creature_versions AS MATERIALIZED (
  SELECT n.entry_id,n.revision_id,n.name,n.aliases,n.typed_fields,n.plain_text,n.canonical_payload,n.source_id,n.file_id,f.mime_type,s.title AS source_title,s.edition,s.language,s.publication_code,s.publication_revision,s.source_priority,lower(n.name) AS sort_title,
    coalesce(((SELECT field->'value'->>'numerator' FROM jsonb_array_elements(n.typed_fields) field WHERE field->>'key'='challenge-rating'))::numeric / nullif(((SELECT field->'value'->>'denominator' FROM jsonb_array_elements(n.typed_fields) field WHERE field->>'key'='challenge-rating'))::numeric,0),0) AS cr_value,
    row_number() OVER (PARTITION BY n.entry_id ORDER BY s.source_priority DESC,n.indexed_at DESC,n.revision_id) AS source_rank
  FROM nfs_index_entries n JOIN sources s ON s.id=n.source_id JOIN files f ON f.id=n.file_id AND f.source_id=s.id
  WHERE ${access.sql} AND s.deleted_at IS NULL AND f.deleted_at IS NULL AND n.lifecycle='active' AND n.entry_type='monster'
), accessible_creatures AS MATERIALIZED (SELECT creature_version.*, (SELECT jsonb_agg(jsonb_build_object('sourceId',source_version.source_id,'title',source_version.source_title,'code',source_version.publication_code,'revision',source_version.publication_revision,'revisionId',source_version.revision_id) ORDER BY source_version.source_priority DESC,source_version.revision_id) FROM accessible_creature_versions source_version WHERE source_version.entry_id=creature_version.entry_id) AS source_versions FROM accessible_creature_versions creature_version WHERE creature_version.source_rank=1) ` }; }
function creatureFilters(params: unknown[], options: CreatureListOptions | Omit<CreatureListOptions, "limit" | "cursor">): string { const filters = ["1=1"];
  const field = (key: string) => `(SELECT item->'value' FROM jsonb_array_elements(creature.typed_fields) item WHERE item->>'key'='${key}')`;
  if (options.sizes?.length) filters.push(`${field("size")} #>> '{}' = ANY($${params.push(options.sizes)}::text[])`);
  if (options.types?.length) filters.push(`${field("creature-type")} #>> '{}' = ANY($${params.push(options.types)}::text[])`);
  if (options.alignment) filters.push(`${field("alignment")} #>> '{}' ILIKE $${params.push(`%${escapeLike(options.alignment)}%`)} ESCAPE '\\'`);
  if (options.challenges?.length) filters.push(`creature.cr_value = ANY($${params.push(options.challenges.map(challengeRatingNumber))}::numeric[])`);
  if (options.minChallenge) filters.push(`creature.cr_value >= $${params.push(challengeRatingNumber(options.minChallenge))}::numeric`);
  if (options.maxChallenge) filters.push(`creature.cr_value <= $${params.push(challengeRatingNumber(options.maxChallenge))}::numeric`);
  if (options.query) filters.push(`(creature.name ILIKE $${params.push(`%${escapeLike(options.query)}%`)} ESCAPE '\\' OR EXISTS (SELECT 1 FROM jsonb_array_elements_text(creature.aliases) alias WHERE alias ILIKE $${params.length} ESCAPE '\\'))`);
  if ("cursor" in options && options.cursor) { const cursor = decodeCursor(options.cursor); params.push(cursor.cr, cursor.title, cursor.id); filters.push(`(creature.cr_value,creature.sort_title COLLATE "C",creature.entry_id) > ($${params.length - 2}::numeric,$${params.length - 1} COLLATE "C",$${params.length})`); }
  return filters.join(" AND "); }
function validateOptions(options: CreatureListOptions | Omit<CreatureListOptions, "limit" | "cursor">): void { if ((options.types?.length ?? 0) > 20 || options.types?.some((value) => !value.trim() || value.length > 160)) throw new CreatureReadInputError("Invalid creature type."); if (options.alignment !== undefined && (!options.alignment.trim() || options.alignment.length > 160)) throw new CreatureReadInputError("Invalid creature alignment."); if (options.query !== undefined && (!options.query.trim() || options.query.length > 120)) throw new CreatureReadInputError("Invalid creature query."); if ("limit" in options && options.limit !== undefined && (!Number.isSafeInteger(options.limit) || options.limit < 1 || options.limit > 100)) throw new CreatureReadInputError("limit must be from 1 to 100."); if (options.minChallenge && options.maxChallenge && challengeRatingNumber(options.minChallenge) > challengeRatingNumber(options.maxChallenge)) throw new CreatureReadInputError("Minimum CR cannot exceed maximum CR."); if ("cursor" in options && options.cursor) decodeCursor(options.cursor); }
function mapList(row: CreatureRow): CreatureListEntry { return { id: row.entry_id, revisionId: row.revision_id, title: row.name, aliases: stringArray(row.aliases), summary: firstSentence(row.plain_text), edition: row.edition, language: row.language, source: { id: row.source_id, title: row.source_title, code: row.publication_code, revision: row.publication_revision }, ...creatureProjectionFromTypedFields(row.typed_fields) }; }
function mapDetail(row: CreatureRow): CreatureDetail { const base = mapList(row); const payload = row.canonical_payload; const citations = Array.isArray(payload.citations) ? payload.citations.flatMap((value, index) => { if (!isRecord(value) || (value.page !== null && !Number.isSafeInteger(value.page)) || typeof value.quote !== "string") return []; const page = value.page === null ? null : Number(value.page); const sourceUrl = typeof value.sourceUrl === "string" && /^https:\/\//.test(value.sourceUrl) ? value.sourceUrl : null; return [{ id: typeof value.citationId === "string" ? value.citationId : `citation-${index + 1}`, quote: value.quote, section: typeof value.section === "string" ? value.section : base.title, page, sourceId: row.source_id, fileId: row.file_id, previewUrl: row.mime_type === "application/pdf" && page !== null ? `/api/citations/preview?sourceId=${encodeURIComponent(row.source_id)}&fileId=${encodeURIComponent(row.file_id)}&page=${page}` : null, sourceUrl, sourceDetailUrl: `/api/sources/${encodeURIComponent(row.source_id)}`, fieldPath: typeof value.fieldPath === "string" ? value.fieldPath : null }]; }) : []; return { ...base, body: row.plain_text, citations, sourceVersions: mapSourceVersions(row.source_versions), sourceVersion: mapSourceVersion(payload.sourceVersion) }; }
function encodeCursor(row: CreatureRow): string { return Buffer.from(JSON.stringify({ v: 1, cr: row.cr_value, title: row.sort_title, id: row.entry_id })).toString("base64url"); }
function decodeCursor(value: string): { cr: string; title: string; id: string } { try { if (value.length > 512) throw new Error(); const item = JSON.parse(Buffer.from(value, "base64url").toString()); if (!isRecord(item) || item.v !== 1 || typeof item.cr !== "string" || !/^\d+(?:\.\d+)?$/.test(item.cr) || typeof item.title !== "string" || typeof item.id !== "string" || !/^[a-z0-9](?:[a-z0-9-]{0,126}[a-z0-9])?$/.test(item.id)) throw new Error(); return { cr: item.cr, title: item.title, id: item.id }; } catch { throw new CreatureReadInputError("Invalid creature cursor."); } }
function mapSourceVersions(value: unknown): CreatureDetail["sourceVersions"] { return Array.isArray(value) ? value.flatMap((item) => isRecord(item) && typeof item.sourceId === "string" && typeof item.title === "string" && typeof item.revisionId === "string" ? [{ sourceId: item.sourceId, title: item.title, code: typeof item.code === "string" ? item.code : null, revision: typeof item.revision === "string" ? item.revision : null, revisionId: item.revisionId }] : []) : []; }
function mapSourceVersion(value: unknown): CreatureDetail["sourceVersion"] { if (!isRecord(value) || typeof value.url !== "string" || typeof value.fingerprintSha256 !== "string" || typeof value.rawBlobPath !== "string" || typeof value.fetchedAt !== "string" || typeof value.fileChecksumSha256 !== "string" || !isRecord(value.index) || typeof value.index.url !== "string" || typeof value.index.fingerprintSha256 !== "string" || typeof value.index.rawBlobPath !== "string" || typeof value.index.fetchedAt !== "string" || typeof value.index.cardFingerprintSha256 !== "string") return null; return { url: value.url, fingerprintSha256: value.fingerprintSha256, rawBlobPath: value.rawBlobPath, fetchedAt: value.fetchedAt, fileChecksumSha256: value.fileChecksumSha256, index: { url: value.index.url, fingerprintSha256: value.index.fingerprintSha256, rawBlobPath: value.index.rawBlobPath, fetchedAt: value.index.fetchedAt, cardFingerprintSha256: value.index.cardFingerprintSha256 } }; }
function normalizeIdentifier(value: string): string { const normalized = typeof value === "string" ? value.normalize("NFC").trim() : ""; if (!normalized || normalized.length > 256) throw new CreatureNotFoundError(); return normalized; }
function escapeLike(value: string): string { return value.trim().replace(/[\\%_]/g, "\\$&"); } function stringArray(value: unknown): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; } function firstSentence(value: string): string { return value.split(/(?<=[.!?])\s/u, 1)[0].slice(0, 240); } function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
