"use client";
import Link from "next/link";
import { useUiLanguage } from "../../components/ui/i18n";
import { CREATURE_SIZES, formatChallengeRating } from "../../server/compendium/creature-schema";
import type { CreatureListEntry, CreatureListOptions } from "../../server/compendium/creature-read-service";
const SIZE_RU: Record<string, string> = { tiny: "Крошечный", small: "Маленький", medium: "Средний", large: "Большой", huge: "Огромный", gargantuan: "Громадный" };
export function BestiaryList({ creatures, count, nextHref, options }: Readonly<{ creatures: readonly CreatureListEntry[]; count: number; nextHref: string | null; options: CreatureListOptions }>) { const { language, t } = useUiLanguage(); const size = (value: string) => language === "ru" ? SIZE_RU[value] ?? value : value[0].toUpperCase() + value.slice(1); return <div className="bestiary-page">
  <header className="bestiary-heading"><p className="bestiary-kicker">D&D 5e / 5.5e</p><h1>{t("bestiaryCatalog")}</h1><p>{t("bestiaryCatalogDescription")}</p></header>
  <form className="bestiary-filters" method="get" action="/bestiary"><label>{t("creatureName")}<input name="q" defaultValue={options.query ?? ""} maxLength={120} /></label><label>{t("creatureType")}<input name="type" defaultValue={options.types?.join(",") ?? ""} maxLength={160} /></label><label>{t("alignment")}<input name="alignment" defaultValue={options.alignment ?? ""} maxLength={160} /></label><label>{t("crMin")}<input name="crMin" defaultValue={options.minChallenge ? formatChallengeRating(options.minChallenge) : ""} inputMode="numeric" /></label><label>{t("crMax")}<input name="crMax" defaultValue={options.maxChallenge ? formatChallengeRating(options.maxChallenge) : ""} inputMode="numeric" /></label><fieldset><legend>{t("creatureSize")}</legend><div className="bestiary-size-grid">{CREATURE_SIZES.map((value) => <label key={value}><input type="checkbox" name="size" value={value} defaultChecked={options.sizes?.includes(value)} />{size(value)}</label>)}</div></fieldset><div className="bestiary-filter-actions"><button type="submit">{t("applyFilters")}</button><Link href="/bestiary">{t("clearFilters")}</Link></div></form>
  <div className="bestiary-results-heading"><strong>{t("creatureResults", { count })}</strong></div>{creatures.length === 0 ? <p className="bestiary-empty">{t("noCreatures")}</p> : <ol className="bestiary-list">{creatures.map((creature) => <li key={creature.id}><Link href={`/bestiary/${creature.id}`}><span className="cr-badge">CR {formatChallengeRating(creature.challengeRating)}</span><span><strong>{creature.title}</strong><small>{size(creature.size)} · {creature.creatureType}{creature.alignment ? ` · ${creature.alignment}` : ""}</small></span></Link><p>{creature.summary}</p><footer>{creature.source.code ?? creature.source.title}{creature.source.revision ? ` · ${creature.source.revision}` : ""}</footer></li>)}</ol>}{nextHref ? <Link className="bestiary-next" href={nextHref} rel="next">{t("nextPage")}</Link> : null}
</div>; }
